files:
  - path: "./data/EVme KM-3.xlsx"
    type: "excel"
  - path: "./data/Factsheet.xlsx"
    type: "excel"
  - path: "./data/FAQ - 2wheels.xlsx"
    type: "excel"
  - path: "./data/FAQ_Rent.xlsx"
    type: "excel"
  - path: "./data/ปัญหารถที่พบบ่อย.xlsx"
    type: "excel"
  - path: "./data/questions1.csv"
    type: "csv"

max_answers: 1